#! /bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh
picom  &
xsetroot -cursor_name left_ptr
feh --bg-fill --randomize ~/Pictures/Wallpapers/* &
bspc monitor -d I II III IV V

# config
bspc config border_width         2
bspc config window_gap          10
bspc config split_ratio          0.52
bspc config focus_follows_pointer true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
